### ISSUE TITLE
Add PHI-Canto specific documentation for physical interactions

### ISSUE THREAD

**Issue by CuzickA** [PHI-base/canto-docs#14]
https://canto.phi-base.org/docs/physical_interaction_annotation

@jseager7 whilst writing the PHI-Canto manuscript I was thinking about the best way to illustrate the Physical interaction annotations. My two thoughts were either
1) as another supplementary file
2) as a screenshot in the Help documentation.

I think my preference would be option 2 as future users may just look at the Help and not the manuscript.

Whilst writing up the section on disease names I noticed that we have such good screenshots in the Help documentation that it seems best to direct readers here rather than generate an additional supplementary file. https://canto.phi-base.org/docs/disease_annotation

**Comment by CuzickA** [comment]
Just remembered that we are planning on including the Help documentation itself as a supplementary file. Therefore, it would be really good to have a Physical interaction screenshot example within this documentation.

**Comment by CuzickA** [comment]
A possible example from PMID:31804478
![image](https://user-images.githubusercontent.com/11753634/144853403-ceb1a1ea-4afe-467f-84f7-8d1bc780d37f.png)

**Comment by jseager7** [comment]
I agree, but the only problem is that this documentation is currently shared with PomBase, so if we want a screenshot that's tailored to PHI-base then we'll need to create our own copy of the page. That's not difficult to do, but it does mean that we won't be synced with any future changes to the Physical Interaction documentation that are added by PomBase.

**Comment by CuzickA** [comment]
I think it would be useful to have a screenshot tailored to PHI-base. It will be easier for PHI-Canto curators to follow. 
I'll add it to the agenda to discuss on Monday.

If PomBase make changes to their physical interactions page could we set up some sort of notification and then manually make the changes to our PHI-Canto page?

**Comment by jseager7** [comment]
> I think it would be useful to have a screenshot tailored to PHI-base. It will be easier for PHI-Canto curators to follow.
I'll add it to the agenda to discuss on Monday.

I think we should just go ahead and do it. I was mentioning PomBase mostly so you were just aware of the fact. We've already gone out of sync with PomBase for most of the documentation to make it easier for curators to follow. The only thing that might need discussion is which example image we should use (note that we could simulate any interaction we want for the purposes of the documentation). 

> If PomBase make changes to their physical interactions page could we set up some sort of notification and then manually make the changes to our PHI-Canto page?

I'll try and keep an eye on the repository commit log. There might be tools to watch for changes to files on GitHub but I don't know of any. Expecting PomBase to notify us probably won't be reliable without tool support.

**Comment by CuzickA** [comment]
Great. When you have time, please could you go ahead and add in the example image above? It might be worth removing the comment if possible.

The example above comes from one of the initial set of trial publications and is mentioned in the PHI-Canto manuscript.

Just to note: This example is a non-gene-for-gene example with PHI phenotype annotations. There will also be sessions with gene-for-gene phenotype annotations and a Physical Interaction. The actual 'physical interaction annotation' is the same for both so we probably don't need screenshots of both, but it could be useful to add this information into the Help text.

**Comment by jseager7** [comment]
It will be closed automatically when the pull request at #17 is merged. I was just waiting to apply the changes in issue #15 first.
