### ISSUE TITLE
Add information on curating effectors using GO BP term

### ISSUE THREAD

**Issue by CuzickA** [PHI-base/canto-docs#15]
We need to make it clear to curators that if they are curating a pathogen effector it is essential that they make the GO BP annotation to 'GO:0140418 effector-mediated modulation of host process by symbiont' or one of its descendants for the data to be displayed correctly in PHI-base 5.

@jseager7 do you think we could slot it into this section? Maybe just under the 'Pathogen-host interaction phenotype heading'
We could add it as text (maybe red text) and then link to the section on how to make the actual GO annotation earlier in the document.
Text could read something like "Please note that if you are curating a pathogen effector within a PHI it is essential that a GO BP annotation is also made to the term 'GO:0140418 effector-mediated modulation of host process by symbiont' or one of its descendants for the data to be displayed correctly in PHI-base." We might also want to add 'curating a pathogen effector' to the contents table to make it easy to find.
![image](https://user-images.githubusercontent.com/11753634/145043761-72ebc9b6-94b1-4836-baa7-26220224cf6d.png)

**Comment by CuzickA** [comment]
> @CuzickA Here's the draft text. I'm planning to insert it just before the heading for 'The phenotype curation process'.
> 
> **Please note** that if you are curating a pathogen effector within a pathogen–host interaction, it is essential that you also make a GO Biological Process annotation on the pathogen gene involved in the interaction, using the GO term "effector-mediated modulation of host process by symbiont" ([GO:0140418](http://purl.obolibrary.org/obo/GO_0140418)) or one of its child terms. This will allow the data to be displayed correctly in PHI-base. See the instructions for Gene Ontology Annotation for further guidance on making a GO Biological process annotation.

@jseager7 sounds good.

I would just add an extra sentence here about making MF annotations when the information is known.
'In some cases it may also be possible to annotate a GO molecular function to the pathogen gene, this can be connected to the GO biological process 'effector-mediated...' term via the annotation extension part_of'. 
This could be inserted before 'See the instructions...', as it is secondary in importance to making the GO BP annotation.

**Comment by CuzickA** [comment]
> > We might also want to add 'curating a pathogen effector' to the contents table to make it easy to find.
> 
> This currently only works if we have a heading to link to. If it would be worth adding a more detailed section about the curation of effectors in general then it could deserve its own heading. Otherwise we could just have two links to the same heading (Pathogen-host interaction phenotype) with different names.

Hmmm... it would be nice to have a 'curating a pathogen effector' section but for now I think we should just make sure the above information about annotating the GO BP and GO MF (if known) is in the main text as planned. 
Moving forward when we have the new hire working on effector curator and author curation feedback we can decide on whether to create an additional 'effector' section and where the common problems arise.

**Comment by jseager7** [comment]
@CuzickA Here's the updated text (additions in bold).

> … if you are curating a pathogen effector within a pathogen–host interaction, it is essential that you also make a GO Biological Process annotation on the pathogen gene involved in the interaction, using the GO term "effector-mediated modulation of host process by symbiont" ([GO:0140418](http://purl.obolibrary.org/obo/GO_0140418)) or one of its child terms. This will allow the data to be displayed correctly in PHI-base. **In some cases, it may also be possible to annotate a GO Molecular Function on the pathogen gene by adding a 'part_of' annotation extension to the GO:0140418 term.** See the instructions for [Gene Ontology Annotation](go_annotation) for further guidance on making a GO Biological process annotation.

The new text makes me wonder whether the GO annotation help page would be a better place for this information in the long term. I think this paragraph is a bit off-topic considering it's on the page for phenotype annotations, but we can leave it here for now.

Once the text is moved we could still have a reminder here about how the curator needs to complement the PHI phenotype annotations with a GO BP annotation, plus a link to the new section on the Gene Ontology Annotation help page (or wherever we decide to move the text).

**Comment by CuzickA** [comment]
Thanks @jseager7 

could you just add bold text below please
 'part_of' annotation extension to the GO:0140418 term **or descendant**.

I'll open a new ticket about 'curating a pathogen effector' text and link it to this ticket to record the discussion. I think we can make a decision in the future on this based on user testing and feedback.

**Comment by CuzickA** [comment]
Just spotted something else

In some cases, it may also be possible to annotate a GO Molecular Function on the pathogen gene **and then** adding a 'part_of' annotation extension to the GO:0140418 term **or descendant**.

The GO MF is a separate annotation with the GO BP effector term connected as an AE.

**Comment by jseager7** [comment]
@CuzickA Thanks for clarifying that. Somehow I had forgotten how the 'part_of' extension worked. Is the text below accurate? 

> In some cases, it may also be possible to annotate a pathogen gene with GO:0140418 (or any of its child terms) by adding the term as a 'part_of' annotation extension on a GO Molecular Function annotation.

I'm assuming that the MF annotation _doesn't rely on_ a separate BP annotation already existing with GO:0140418 on it. Is that true? Or is the intention that whenever GO:0140418 is annotated as a BP that it should _also_ have relevant MF annotations with GO:0140418 as a part_of extension? (Similar to how a PHI phenotype effector should be complemented with a GO BP annotation).

**Comment by CuzickA** [comment]
> Or is the intention that whenever GO:0140418 is annotated as a BP, that it should also have relevant MF annotations with GO:0140418 as a part_of extension? (Similar to how a PHI phenotype effector should be complemented with a GO BP annotation).

GO BP Annotation 1
For pathogen effectors the GO BP term or child term is an essential annotation so we can use the high level 'effector' tag in PHI5 display. 
GO MF Annotation 2
In some cases a MF is also known. When the MF is also known this annotation can be made and an AE 'part of' can use the BP term GO:0140418 or descendant.
PHIPO Annotation 3 
Add PHIPO annotations (can also be done before the GO annotations if easier)

This text is still not quite right

> In some cases, it may also be possible to annotate a pathogen gene with GO:0140418 (or any of its child terms) by adding the term as a 'part_of' annotation extension on a GO Molecular Function annotation.

I suggest something more like this
In some cases, it may also be possible to annotate a GO Molecular Function on the pathogen gene and then add a 'part_of' annotation extension with the GO:0140418 term or descendant.

**Comment by jseager7** [comment]
@CuzickA Here's my suggested text, which is your suggestion with a few minor changes:

> In some cases, you will also need to annotate a GO Molecular Function on the pathogen gene and then add a 'part_of' annotation extension containing the GO:0140418 term or any of its child terms.

The changes are:

* replace 'it may also be possible' with 'you will also need to', because I think the text 'In some cases' already indicates that the step is optional and we probably want to encourage the curator to add the MF where it is known and when the BP is already annotated;
* in the text 'with the GO:0140418 term', replace 'with' with 'containing' to make it clearer how annotation extensions relate to ontology terms; 
* replace 'descendant' with 'any of its child terms' to match the earlier wording.

**Comment by jseager7** [comment]
Now that I think about it, maybe 'In some cases' should be replaced by the actual case where we want to add the MF annotation, based on your explanation above:

> Where the molecular function of the effector is known, you will also need to annotate a GO Molecular Function…

**Comment by CuzickA** [comment]
@jseager7 shall we go ahead with this text for now?

Where the molecular function of the effector is known, you will also need to annotate a GO Molecular Function on the pathogen gene and then add a 'part_of' annotation extension containing the GO:0140418 term or any of its child terms.

**Comment by jseager7** [comment]
Fixed by 6151c0df84d46cdae931c2d80a029aa279bd9e1b and 5fcee26b6d29276dd78758f226c29e2f337dc8ab.
