### ISSUE TITLE
Add subheading for curating a pathogen effector

### ISSUE THREAD

**Issue by CuzickA** [PHI-base/canto-docs#18]
See discussion #15 

We may need a 'section' on how to curate pathogen effectors correctly with GO terms. We have currently decided to add a few sentences of text within the 'Phenotype curation process' of the Help documentation.

We can wait and see what feedback we get from PHI-Canto users and decide in the future if we need to add additional text.

**Comment by CuzickA** [comment]
https://canto.phi-base.org/docs/phipo_annotation#pathogen_host_interaction_phenotypes

For manuscript 'issues' Table

To make it easier for people to find 'effector' curation within the Help text

**Comment by jseager7** [comment]
The PomBase documentation for their phenotype annotation type has sections for general and specific phenotype curation tips ([link](https://curation.pombase.org/pombe/docs/fypo_annotation#gentips)). We removed these sections from our copy of the documentation because we couldn't think of anything to include at the time. Maybe we should consider restoring these sections now and moving the text there?

Note that a phenotype tips section could also be used for including specific help with chemistry phenotypes (see #21).

**Comment by CuzickA** [comment]
Yes, I was also wondering about the 'phenotype tips' documentation. 
I was hoping that we could make a few quick additions to the main Help document so that we have it ready for the manuscript. It will take more time to develop the 'phenotype tips' documentation and perhaps this could be done in the future after the manuscript is completed and based on User feedback.

**Comment by jseager7** [comment]
> I was hoping that we could make a few quick additions to the main Help document so that we have it ready for the manuscript.

In that case, we need to decide exactly where the section will go on the page – unless you just wanted to introduce another subheading above the existing paragraph: something like 'Curating pathogen effectors'.

**Comment by CuzickA** [comment]
Yes, maybe we could add the suggested subheading above the 'please note' text

![image](https://user-images.githubusercontent.com/11753634/155101139-8fce9f20-beda-4162-a566-471ff6bf32c8.png)

**Comment by jseager7** [comment]
I've added the section heading and made some further amendments to the text to fix some mistakes. Here's how it will look.

- - -

#### Curating pathogen effectors

If you are curating a pathogen effector within a pathogen–host interaction, it is essential that you also make a GO Biological Process annotation on the pathogen gene involved in the interaction, using the GO term "effector-mediated modulation of host process by symbiont" ([GO:0140418](http://purl.obolibrary.org/obo/GO_0140418)) or one of its child terms. This will allow the data to be displayed correctly in PHI-base.

Where the molecular function of the effector is known, you will also need to annotate a GO Molecular Function on the pathogen gene. This molecular function annotation must have a 'part_of' annotation extension that links to GO:0140418 or any of its child terms. See the instructions for [Gene Ontology Annotation](go_annotation) for further guidance on making GO annotations.

**Comment by CuzickA** [comment]
@jseager7 has this change been uploaded to the Help documentation? I can't see it.

**Comment by jseager7** [comment]
No. I tend to close the issues once the source code changes are committed to this repository, because the actual code is deployed to the pombase/canto repository and I tend to deploy the changes in batches, in order to save time. If you'd prefer to have issues left open until the actual code is deployed, then please let me know.

**Comment by CuzickA** [comment]
Okay, thanks for explaining. I tend to think that once a ticket has been closed the task has been completed.

**Comment by jseager7** [comment]
Okay, I've added a 'deploy' label to both this and issue #19. That will let me know that the code changes are done but they're waiting to be deployed. I'll close both issues once I've updated Canto.

**Comment by jseager7** [comment]
Implemented by https://github.com/pombase/canto/commit/7aeafa4eb16afc9568f4e124c874ba569fb0e31c, and deployed on our servers.
