### ISSUE TITLE
Add 'delivery mechanism' to experimental conditions

### ISSUE THREAD

**Issue by CuzickA** [PHI-base/canto-docs#19]
https://canto.phi-base.org/docs/phipo_annotation#experimental_conditions

For manuscript 'issues' Table

**Comment by jseager7** [comment]
Here's some draft text (additions in **bold**). I'm assuming we only need to add delivery mechanisms to the existing list. The position in the list is provisional.

- - -

* Minimal medium vs. rich medium
* Agar plates vs. liquid medium
* **Gene delivery mechanism (e.g. agrobacterium, heterologous organism, pathogen inoculation)**
* Addition of certain chemicals; for instance, in a salt stress experiment it may be of interest to note what salts were added. (Note that in cases where the PHIPO term already describes sensitivity or resistance to a certain chemical, it is not necessary to specify that same chemical in the experimental conditions.)

- - -
@CuzickA Are these conditions strictly about _gene_ delivery (that is, delivering foreign genetic material into host cells), or is there more to it? The names like 'pathogen inoculation' seem to imply that these terms are variously about delivering genetic material and delivering whole organisms.

**Comment by CuzickA** [comment]
Yes, I think this is a good place to add it.

I would omit 'Gene' and just call it 'Delivery mechanism'.

We can wait for user feedback and provide more information in the future if required.

**Comment by CuzickA** [comment]
@jseager7 has this change been uploaded to the Help doc yet?

**Comment by jseager7** [comment]
It's not deployed yet. See https://github.com/PHI-base/canto-docs/issues/18#issuecomment-1060384928 for my reasoning.

**Comment by jseager7** [comment]
Implemented by https://github.com/pombase/canto/commit/7aeafa4eb16afc9568f4e124c874ba569fb0e31c, and deployed on our servers.
