### ISSUE TITLE
Add text describing 'RNA level' and 'Protein level' to help documentation

### ISSUE THREAD

**Issue by CuzickA** [PHI-base/canto-docs#2]
There may already be some PomBase 'detailed text' for this that we can point to in a similar manner to the GO documentation. 

Note: grouped under 'qualitative gene expression' in PomBase
![image](https://user-images.githubusercontent.com/11753634/98352141-8902db80-2015-11eb-9389-b2fbb4761f06.png)

**Comment by jseager7** [comment]
The documentation is already included in Canto, so the fix should be as simple as adding a few links to our index page. In PomBase's version of Canto, both RNA level and Protein level link to the same help page: [Curating gene expression](https://curation.pombase.org/pombe/docs/gene_expression).

**Comment by jseager7** [comment]
I've added links for both annotation types to the index page. Note to self: the gene_expression help page will need to be linked to the PHI-base documentation folder in the Canto repository.
