### ISSUE TITLE
Add subheading about curating WT control metagenotypes where possible

### ISSUE THREAD

**Issue by CuzickA** [PHI-base/canto-docs#20]
Currently mentioned here

https://canto.phi-base.org/docs/genotypes#metagenotype_management

Is this clear enough and easy enough to find within the Help document?

For 'issues' table.

**Comment by jseager7** [comment]
I think it would be clearer under a heading. Looking at the document again, I wonder if the existing text would be better placed in a subsection at the end of the 'Creating metagenotypes' section, since the section it's currently in is more about how to navigate to the Metagenotype Management page (plus the text has been inserted before an image that should be placed before the previous paragraph).

**Comment by jseager7** [comment]
Here's what my suggestion would look like. The new section is at the bottom. I tweaked the first sentence slightly to make it follow on from the previous section.

![image](https://user-images.githubusercontent.com/37659591/154974234-030416bb-6418-45a3-9a89-8a8a2326588e.png)

**Comment by CuzickA** [comment]
This looks good to me. 

Maybe we should add in text 
'Please note there may be cases where it is not possible to create a control metagenotype.'

Just so that Curators don't panic if they cannot create the control metagenotype eg controls with a vector only construct (no pathogen gene) infiltrated into a plant leaf.

**Comment by CuzickA** [comment]
Just to note we might want to provide a link to the new section 'creating control metagenotypes' in the last paragraph of text here describing 'using wild type alleles in genotypes'

![image](https://user-images.githubusercontent.com/11753634/154976845-d61a394b-8c19-47ee-a67c-8cdde3dad6f0.png)

**Comment by jseager7** [comment]
> Just so that Curators don't panic if they cannot create the control metagenotype eg controls with a vector only construct (no pathogen gene) infiltrated into a plant leaf.

Should we list any of the examples where we currently know it's not feasible to curate control metagenotypes?

**Comment by jseager7** [comment]
> Just to note we might want to provide a link to the new section 'creating control metagenotypes' in the last paragraph of text here describing 'using wild type alleles in genotypes'

Agreed. I can do that as part of these changes.

**Comment by CuzickA** [comment]
> > Just so that Curators don't panic if they cannot create the control metagenotype eg controls with a vector only construct (no pathogen gene) infiltrated into a plant leaf.
> 
> Should we list any of the examples where we currently know it's not feasible to curate control metagenotypes?

We could add the 'vector only' control example.

**Comment by CuzickA** [comment]
Hi @jseager7 has this been done and waiting for 'deploy' like #18 and #19?

**Comment by jseager7** [comment]
This hasn't been done yet: the image above was just a mockup. I'm a bit unsure what to include for the "vector only control example". Do you think you could amend your following suggestion:

> 'Please note there may be cases where it is not possible to create a control metagenotype.'

So that it includes an example of the vector only control case, as you mentioned below?

> eg controls with a vector only construct (no pathogen gene) infiltrated into a plant leaf.

**Comment by CuzickA** [comment]
How about
'Please note there may be cases where it is not possible to create a control metagenotype, for example, where an empty vector (without a pathogen gene) is infiltrated into a plant leaf as a control experiment.'

**Comment by jseager7** [comment]
Yep, that looks fine, thanks. I'll make the changes now.

**Comment by jseager7** [comment]
Implemented by https://github.com/pombase/canto/commit/7aeafa4eb16afc9568f4e124c874ba569fb0e31c, and deployed on our servers.
