### ISSUE TITLE
Add example or subheading for chemistry annotations

### ISSUE THREAD

**Issue by CuzickA** [PHI-base/canto-docs#21]
https://canto.phi-base.org/docs/phipo_annotation#single_species_phenotypes

Required for 'issues' table.

**Comment by jseager7** [comment]
I think this section should either go at the very end of the document, or before the 'Annotation extensions' section. I realise that it might be easy to miss the section if we place it later, but we could solve this by having a table of contents on the page (maybe we should think about doing that for all the help pages).

**Comment by CuzickA** [comment]
Could we include it within the 'single species phenotype' section?

**Comment by jseager7** [comment]
> Could we include it within the 'single species phenotype' section?

That subheading is in the 'Starting a phenotype annotation' section, so it's really only meant to cover how to _start_ a phenotype annotation. If that's all we need to describe for the chemistry phenotypes (how you start them), then we could include it at the end of that section.

Note that there are also sub-subheadings for the Genotype Management workflow and the Single allele workflow, and we probably don't want to repeat the instructions for chemistry phenotypes in there. We could just note in the chemistry phenotype section that chemistry phenotypes can also be made on single or multiple alleles.

**Comment by CuzickA** [comment]
Maybe we could add some extra text under the 'selecting a PHIPO term' section.

We have the single species (pathogen and host) and PHI branch groupings of PHIPO terms that PomBase does not have. We could add some text about single species PHIPO terms and add Resistance and Sensitivity to chemical XX as example PHIPO terms and then do something similar for the PHI branch terms.

@jseager7 what do you think? 


![image](https://user-images.githubusercontent.com/11753634/155101980-2251c13e-d3e6-4f5a-85f2-ff95a280268b.png)

**Comment by CuzickA** [comment]
Slightly off topic but @jseager7 and I were just discussing the problem of some of the AE infective ability terms eg 'unaffected pathogenicity' being selected as MAIN PHIPO annotation terms due to an issue with the 'in_subset' grouping.

Perhaps in the new extra text above we could give egs of correct PHI branch PHIPO terms and then make a 'please note' comment about not using terms such 'unaffected pathogenicity' here but as an AE instead and link to the AE section.

**Comment by jseager7** [comment]
> Maybe we could add some extra text under the 'selecting a PHIPO term' section.
> We have the single species (pathogen and host) and PHI branch groupings of PHIPO terms that PomBase does not have. We could add some text about single species PHIPO terms and add Resistance and Sensitivity to chemical XX as example PHIPO terms and then do something similar for the PHI branch terms.

I'm fine with this, but I'm not sure what the text should say. It seems like the only reason to mention the split between single-species and pathogen-host terms is to clarify where certain annotations are made (e.g. if you want to annotate chemical resistance, then use a single-species phenotype; if you want to annotate pathogen growth in or on the host, use a pathogen-host interaction phenotype).

Could you suggest an outline of what the text should say, and maybe which terms or types of phenotype we should use as examples?

**Comment by jseager7** [comment]
> Has 'PHIPO' been spelt out as the 'Pathogen Host Interaction Phenotype Ontology' within the Help document? -Something to check.

I've just checked, and no, we haven't expanded the abbreviation anywhere. Would you want it defined in the Introduction section of the Curating phenotypes page?

**Comment by CuzickA** [comment]
Possible draft text for under 'selecting a PHIPO term'

The Pathogen Host Interaction Phenotype Ontology (PHIPO) was created with two branches. A single species branch which includes phenotypes associated with either pathogen or host species singly. Pathogen genotypes can be annotated with single species phenotype terms such as X, X and X. Host genotypes can be annotated with single species terms such as X. The pathogen-host interaction branch of PHIPO includes phenotypes associated with a pathogen-host interaction. Metagenotypes can be annotated with pathogen-host interaction phenotype terms such as X and X.


@jseager7 Let me know what you think -I'm sure the text can be improved! I still need to look up some example terms.

**Comment by CuzickA** [comment]
> > Has 'PHIPO' been spelt out as the 'Pathogen Host Interaction Phenotype Ontology' within the Help document? -Something to check.
> 
> I've just checked, and no, we haven't expanded the abbreviation anywhere. Would you want it defined in the Introduction section of the Curating phenotypes page?

Yes, it would probably make sense to add it in the Introduction section where PHIPO is first mentioned.

**Comment by jseager7** [comment]
The text above seems fine to me. I can make some small changes for clarity but I'll wait until we have the examples before doing that. We can define PHIPO in the introduction and then just use the abbreviated form on the draft text.

**Comment by CuzickA** [comment]
Host egs (they are tricky as we have only annotated with the two terms below, which are quite complicated terms)
presence of effector-independent host hypersensitive response
absence of effector-independent host hypersensitive response

Looks like in PHI-Canto the host phenotype search options are currently the same as the Pathogen phenotypes above.
![image](https://user-images.githubusercontent.com/11753634/157425282-62c79780-be13-4d77-a1c5-ced72471ff81.png)

**Comment by CuzickA** [comment]
> Host egs (they are tricky as we have only annotated with the two terms below, which are quite complicated terms) presence of effector-independent host hypersensitive response absence of effector-independent host hypersensitive response
> 
> Looks like in PHI-Canto the host phenotype search options are currently the same as the Pathogen phenotypes above. ![image](https://user-images.githubusercontent.com/11753634/157425282-62c79780-be13-4d77-a1c5-ced72471ff81.png)

Maybe it would be better to just use 
'Host genotypes can also be annotated with single species terms.' 
in the above planned text. We can add an example term in the future once it has been created in PHIPO and used in annotation.

**Comment by CuzickA** [comment]
PHI a few egs (might need to add extra text about how the term can describe the pathogen within the PHI and the host within the PHI)
absence of pathogen growth on host surface
decreased extent of pathogen-associated host lesions
presence of host-defense induced lesion by host hypersensitive response
stunted host growth during pathogen colonization

From PHI-Canto
![image](https://user-images.githubusercontent.com/11753634/157427701-e44672a4-b5c8-46b2-b210-77c997c9fc51.png)

**Comment by CuzickA** [comment]
How about something like this text


The Pathogen Host Interaction Phenotype Ontology (PHIPO) was created with two branches. A single species branch which includes phenotypes associated with either pathogen or host species singly. Pathogen genotypes can be annotated with single species phenotype terms such as 'sexual spores absent', 'decreased hyphal growth' or Chemistry phenotypes such as 'resistance to voriconazole', 'sensitive to voriconazole' or 'normal growth on voriconazole'. Host genotypes can also be annotated with single species terms. The pathogen-host interaction branch of PHIPO includes phenotypes associated with a pathogen-host interaction. Metagenotypes can be annotated with pathogen-host interaction phenotype terms such as 'absence of pathogen growth on host surface', 'decreased extent of pathogen-associated host lesions', 'presence of host-defense induced lesion by host hypersensitive response' and 'stunted host growth during pathogen colonization'.

**Comment by jseager7** [comment]
@CuzickA Here's my draft of the text. My examples are structured differently because I didn't notice your draft text until just now. 

> PHIPO consists of two branches: a single species branch, which includes phenotypes associated with either pathogen or host species in isolation; and a pathogen-host interaction branch, which includes phenotypes associated with the outcomes of pathogen-host interactions. Pathogen genotypes can be annotated with single species phenotype terms, such as 'resistance to voriconazole', 'sexual spores absent', and 'decreased hyphal growth'. Host genotypes can also be annotated with single species terms, such as 'presence of effector-independent host hypersensitive response'. Metagenotypes can be annotated with pathogen-host interaction phenotype terms, such as 'absence of pathogen growth on host surface' and 'stunted host growth during pathogen colonization'. Note that some terms in the pathogen-host branch describe changes in the pathogen, while other terms describe changes in the host.

I thought it would be better to include at least one host example, even if it's complicated. Do you want me to include the distinction between chemistry phenotypes and the other pathogen phenotypes?

**Comment by CuzickA** [comment]
@jseager7 that looks fine :-). I think we need to mention 'chemistry phenotypes' as this is the section we are referring to from the manuscript table about chemistry phenotypes.

Also we wanted to add about PHIPO being registered with OBOFoundry somewhere in this section.

**Comment by jseager7** [comment]
> Also we wanted to add about PHIPO being registered with OBOFoundry somewhere in this section.

I've added this to the introduction instead since I thought it would be better to mention it earlier. Here's the new text:

> If you want to browse terms in PHIPO, you can use any of the term browsers linked to from PHIPO's page on the [OBO Foundry](https://obofoundry.org/ontology/phipo) (for example, OntoBee or OLS). The OBO Foundry also provides downloads of PHIPO in OWL and OBO formats.

Also, here's the changed text in the Introduction that defines PHIPO (changes in bold).

> A phenotype is any observable characteristic or trait of an organism that results from the interactions between its genotype and the environment. PHI-Canto supports annotation of single- and multi-allele phenotypes on pathogen genotypes, host genotypes and metagenotypes (pathogen and host genotype), **using terms from PHIPO (the Pathogen-Host Interaction Phenotype Ontology)** and additional useful details such as evidence and experimental conditions.

**Comment by jseager7** [comment]
> I think we need to mention 'chemistry phenotypes' as this is the section we are referring to from the manuscript table about chemistry phenotypes.

Okay, here's the amended text:

> Pathogen genotypes can be annotated with single species phenotype terms, such as 'sexual spores absent' and 'decreased hyphal growth', as well as chemistry phenotypes, such as 'resistance to voriconazole', 'sensitive to voriconazole', and 'normal growth on voriconazole'.

**Comment by CuzickA** [comment]
Hi @jseager7, as mentioned this morning the new text describing Chemistry Phenotypes is now under a PHI heading instead of a Single species heading. This seems a bit odd when listed in Table 3 as a single species annotation.
![image](https://user-images.githubusercontent.com/11753634/158184609-adefee79-2b7b-4ab9-a51f-908becb8b93e.png)
This text describes both PHI and single species terms. Can we improve on where this text is located? Its a bit tricky to see where else it would fit looking at the main contents page.

**Comment by CuzickA** [comment]
Okay thanks @jseager7 
Where is this link on the main contents page? Am I missing something?
![image](https://user-images.githubusercontent.com/11753634/158190950-df38f901-9df2-4691-b309-9ca6028b3883.png)

**Comment by jseager7** [comment]
The section isn't linked on the table of contents at the moment, probably because it covers both 'Annotating genotypes' and 'Annotating metagenotypes', so it's not obvious where the link should go.

As a quick fix, we could include a link in both of the above sections in the table of contents, or above the 'Experimental evidence' link, but I wonder whether the 'Curating phenotypes' page really needs restructuring, or splitting up into separate pages for single-species and pathogen-host annotations, so that it fits better with the layout of the table of contents.

**Comment by CuzickA** [comment]
> As a quick fix, we could include a link in both of the above sections in the table of contents

@jseager7 lets do this for now. We can make larger restructuring changes if needed in the future based on user feedback.

**Comment by jseager7** [comment]
Here's how the table of contents will look after this change:

![image](https://user-images.githubusercontent.com/37659591/158357428-b61d6505-d235-4cfc-9b55-d7ae9ec839cd.png)

Does that look okay?

**Comment by CuzickA** [comment]
Just wanted to check, how much of the section will be duplicated? Its a bit hard for me to tell on the Help page. Is it this section 
![image](https://user-images.githubusercontent.com/11753634/158359059-3f828eec-310a-4428-8071-b5bd2c2ba1e0.png)

I'm finding it a bit hard to visualise

**Comment by jseager7** [comment]
Both of the new links in the table of contents (the ones labelled 'The phenotype curation process') will link to the section in your image above when clicked. So, both of the new links will link to the same section of the same page. That makes one of the links redundant, but it's probably clearer to have the links in both sections, as we've discussed.

**Comment by CuzickA** [comment]
Okay thanks for clarifying :-). Lets go with that option for now.

**Comment by jseager7** [comment]
I've deployed this change on both servers now. See https://github.com/pombase/canto/commit/1e27e0a2a5fc1eeaa956c351cdae6105a7eba94c.
