### ISSUE TITLE
Document 'gene-for-gene phenotype' annotation type

### ISSUE THREAD

**Issue by CuzickA** [PHI-base/canto-docs#3]

**Comment by jseager7** [comment]
@CuzickA We'll also need to fill out the broad and specific term suggestions and the additional help text for the annotation type. Here's a copy of the additional help text for pathogen-host interaction phenotypes:

> A pathogen-host interaction phenotype is any observable characteristic or trait of an interaction between a pathogen organism and a host organism; observable characteristics include morphology, development, biochemical or physiological properties, behaviour, and products of behaviour of the organisms. Pathogen-host interaction phenotypes result from the expression of the genes of any of these organisms, as well as the influence of environmental factors (or the interaction between genes and environmental factors).

**Comment by CuzickA** [comment]
Suggest add a new section for 'gene-for-gene interaction phenotype extensions' under here

![image](https://user-images.githubusercontent.com/11753634/104940651-f504a700-59a9-11eb-8a5e-e3e2cd67e2fd.png)

include extensions for
infected tissue
gene for gene interaction (need to draft text)
compared to control (need to draft text)
(disease caused) this will probably be removed in the future

**Comment by jseager7** [comment]
@CuzickA We'd also need edits to the a section under the [Pathogen-host interaction phenotypes](https://github.com/PHI-base/canto-docs/blob/master/docs/phipo_annotation.md#pathogen-host-interaction-phenotypes) heading, since we don't have only one phenotype for pathogen-host interactions anymore.

**Comment by CuzickA** [comment]
![image](https://user-images.githubusercontent.com/11753634/105020367-1bc0ed00-5a3f-11eb-864a-cffd79c67cad.png)
 Hi @jseager7 I think the above comment means adding a 'gene for gene interaction phenotype' section under 'pathogen-host interaction phenotypes' section in image above. 
Text could read
To annotate a gene-for-gene interaction phenotype on a pathogen-host interaction (a metagenotype), go to the Metagenotype Management page and select ‘Annotate gene-for-gene interaction phenotype’ from the list of actions next to the relevant metagenotype.

And the metagenotype image needs updating to show all the current links in blue.

**Comment by jseager7** [comment]
@CuzickA Here's some draft text:

### Phenotype description

(I decided not to add a new section for gene-for-gene phenotypes since I thought adding to the existing text was less repetitive. I think it would help to have a brief explanation of what we mean by a 'gene-for-gene interaction' though.)

"To annotate a phenotype on a pathogen-host interaction (a metagenotype), go to the Metagenotype Management page and select either ‘Annotate pathogen-host interaction phenotype’ or ‘Annotate gene-for-gene phenotype’ from the list of actions next to the relevant metagenotype."

### Gene-for-gene interaction extension

"...describes multiple properties of a gene-for-gene interaction, including: whether a gene conferring disease resistance in the host was molecule was present, absent, or compromised; the presence or absence of a pathogen effector molecule that can be recognized by the host; and whether the interaction caused disease in the host (a compatible interaction) or did not (an incompatible interaction)."

**Comment by jseager7** [comment]
@CuzickA Do you also want the documentation for the 'penetrance' extension included under the gene-for-gene phenotype section as well?

I'm assuming the penetrance extension has the same meaning when used on interaction phenotypes as it does when used on single-species phenotypes. The text for the single-species phenotype version is below:

"...the proportion of a population that shows the phenotype. The penetrance measurement can be qualitative or quantitative."

**Comment by CuzickA** [comment]
> @CuzickA Do you also want the documentation for the 'penetrance' extension included under the gene-for-gene phenotype section?
> 
> I'm assuming the penetrance extension has the same meaning when used on interaction phenotypes as it does when used on single-species phenotypes. The text for the single-species phenotype version is below:
> 
> "...the proportion of a population that shows the phenotype. The penetrance measurement can be qualitative or quantitative."

I'm not sure. If we add it in it will need to be added to both the PHI and GfG sections -perhaps we just leave it in the singles species section. 'Assayed feature' would also need to be added to all sections if we decided to show all available AE.

**Comment by CuzickA** [comment]
I have seen a small typo, and extra _was_

Gene-for-gene interaction: describes multiple properties of a gene-for-gene interaction, including: whether a gene conferring disease resistance in the host _was_ molecule was present,

**Comment by CuzickA** [comment]
Perhaps we should also include the 'disease caused' AE under GfG for now to be consistent with the PHI section. They can both be removed in the future once we have decided how to proceed with the disease names and disabled this AE option in PHI-Canto.

**Comment by CuzickA** [comment]
It would be good to add a link to the GfG interaction phenotype on our contents page

![image](https://user-images.githubusercontent.com/11753634/105035695-5765b200-5a53-11eb-8deb-4b7b91bf5ffc.png)

**Comment by jseager7** [comment]
@CuzickA Thanks for the feedback. I'll fix those issues. Can you suggest a gene for the host side of the interaction? I don't mind if we have to change the pathogen or the pathogen gene to fit.

**Comment by CuzickA** [comment]
We could use this control metagenotype
![image](https://user-images.githubusercontent.com/11753634/105041760-4d47b180-5a5b-11eb-8158-45227d3e3c63.png)

UniProts
A0A2K9YVY7 needs to be manually renamed in PHI-Canto using edit function to AvrStb6+
A0A1D5VHV3 for host stb6

**Comment by jseager7** [comment]
Thanks. I'll copy that to the test session.

**Comment by jseager7** [comment]
@CuzickA I'm just looking at the screenshot below, and I'm not sure it's a good idea to replace it with an example showing a gene-for-gene interaction. The heading is for 'pathogen-host interaction phenotypes' in the general sense, so having the image show a gene-for-gene interaction is arguably less accurate than showing a pathogen-host interaction, because a gene-for-gene interaction is a special (less general) case of a pathogen-host interaction, not the other way round.

If we really want an image that is compatible with both a 'standard' pathogen-host interaction phenotype and a gene-for-gene phenotype, maybe we should use a mutant host gene. Honestly though, I'm not sure it's worth being that precise: the point of the image is just to show which links start a phenotype annotation; we don't even need to show the whole metagenotype, it's only there to help users know where to look.
- - -

![](https://user-images.githubusercontent.com/11753634/105035373-cbec2100-5a52-11eb-91b9-c04c45e6a2f2.png)

**Comment by jseager7** [comment]
I've fixed a few more parts of the documentation where we'd neglected to mention gene-for-gene phenotypes. See commit b82fbf1.

**Comment by CuzickA** [comment]
> @CuzickA I'm just looking at the screenshot below, and I'm not sure it's a good idea to replace it with an example showing a gene-for-gene interaction. The heading is for 'pathogen-host interaction phenotypes' in the general sense, so having the image show a gene-for-gene interaction is arguably less accurate than showing a pathogen-host interaction, because a gene-for-gene interaction is a special (less general) case of a pathogen-host interaction, not the other way round.
> 
> If we really want an image that is compatible with both a 'standard' pathogen-host interaction phenotype and a gene-for-gene phenotype, maybe we should use a mutant host gene. Honestly though, I'm not sure it's worth being that precise: the point of the image is just to show which links start a phenotype annotation; we don't even need to show the whole metagenotype, it's only there to help users know where to look.
> 
> ![](https://user-images.githubusercontent.com/11753634/105035373-cbec2100-5a52-11eb-91b9-c04c45e6a2f2.png)

I was thinking about this too and I agree it may be better to leave the image as it is for now. We can wait and see what author feedback is.

I was wondering whether we needed to restrict the GfG annotation workflow to only metagenotypes with a specified pathogen and host gene. Is this even possible?

This may not be so good for the publication https://github.com/PHI-base/curation/issues/65
where we want to curate a GfG interaction although the host gene is not yet cloned (no UniProt). We should probably discuss this to see if we still want to be able to do this or restrict curators to adding pathogen and host genes for GfG metagenotype.

**Comment by jseager7** [comment]
> I was wondering whether we needed to restrict the GfG annotation workflow to only metagenotypes with a specified pathogen and host gene. Is this even possible?

It's not possible at the moment. We'd need to add a configuration option to each annotation type specifying whether or not it should allow wild-type genotypes.

However, as you mentioned, there are cases where you have to use the wild-type genotype as a placeholder, so I think it would be simpler to just rely on curator guidelines to ensure that curators curate both genes when doing gene-for-gene interactions. In these cases I think it's better to be permissive, and risk some partially incorrect curation, than to be too restrictive, and risk getting no curation at all.

**Comment by CuzickA** [comment]
Once new 'AE inverse GfG interaction' is active we will need to add this to the documentation below (and in other relevant places within the Help doc)

![image](https://user-images.githubusercontent.com/11753634/106448705-0bffca80-647b-11eb-8e7a-c76e8707142d.png)

Draft text
Inverse Gene-for-gene interaction: 
describes multiple properties of an inverse gene-for-gene interaction, including: whether a gene conferring disease susceptibility in the host was present, absent, or compromised; the presence or absence of a pathogen necrotrophic effector molecule that can be recognized by the host susceptibility locus; and whether the interaction caused disease in the host (a compatible interaction) or did not (an incompatible interaction).

**Comment by jseager7** [comment]
@CuzickA I've added the draft text above (still needs to be uploaded). If you don't think there's anything left to do for this issue, feel free to close it.
