### ISSUE TITLE
Document the 'outcome of interaction' annotation extension

### ISSUE THREAD

**Issue by CuzickA** [PHI-base/canto-docs#7]
Add AE text to document 'Curating phenotypes' see also #8 
currently
![image](https://user-images.githubusercontent.com/11753634/104940001-0c8f6000-59a9-11eb-9c99-0676ba74a25c.png)

Add
disease interaction (still need to draft some text here)
~~compared to control (still need to draft some text here)~~ (see https://github.com/PHI-base/canto-docs/issues/8 instead)

**Comment by jseager7** [comment]
@CuzickA Here's some draft text for the 'outcome of interaction' extension. I can't really think of anything more to say than what's obvious. Maybe the documentation should explain how this extension relates to the 'extent of infectivity' extension.

"...describes the overall outcome of the interaction in terms of whether disease was present or absent in the host."

**Comment by CuzickA** [comment]
Sounds good.

The AE disease extension should/can be added to both control and mutant metagenotypes whereas the infective ability be only be added to mutant metagenotypes (I think, with the exception of mutualism present). The usage rules for these AEs are not completely clear yet. Once I have finished my reannotation of all the sessions with metagenotype controls etc hopefully a clearer usage pattern will emerge ;-)

**Comment by jseager7** [comment]
I've added the initial text. I'll leave this issue open until we've resolved the usage rules for the extension.

**Comment by CuzickA** [comment]
I'm going to close this ticket.

It is not always possible to add this AE disease extension to metagenotype annotations. Sometime it is just not relevant to the observed phenotype. Where possible it should be added to both control and mutant metagenotypes.

I think we should wait for some PHI-Canto user feedback to highlight if there are any problems using this AE.
