### ISSUE TITLE
Document the 'compared to control genotype' annotation extension

### ISSUE THREAD

**Issue by CuzickA** [PHI-base/canto-docs#8]

**Comment by jseager7** [comment]
@CuzickA Here's some draft text for the 'compared to control genotype' extension:

"...records a pathogen genotype and a host genotype (combined as a metagenotype) that are used as an experimental control for the genotypes in a gene-for-gene interaction. Usually the control genotypes will be the wild-type genotypes of the pathogen and host, but they may also be mutant genotypes."

**Comment by CuzickA** [comment]
Sounds good @jseager7

**Comment by jseager7** [comment]
The documentation has been updated for both interaction phenotypes now (the gene-for-gene phenotype change was included in commit https://github.com/PHI-base/canto-docs/commit/fa0114d496e62808f3b8b463d1d3b035e55816a4).
